version: '3.8'

services:
  logger:
    container_name: logger
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - vector

  vector:
    container_name: vector
    image: timberio/vector:nightly-debian
    command: ["-c", "/etc/vector/vector.toml"]
    ports:
      - "8686:8686"  # Порт для Prometheus
      - "8080:8080"  # Порт для API
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro # Логи контейнеров
      - /var/run/docker.sock:/var/run/docker.sock:ro             # Для получения инфы о контейнерах
      - ./vector.toml:/etc/vector/vector.toml:ro                 # Конфигурация
    environment:
      - VECTOR_SELF_NODE_NAME=vector

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - vector

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
